### ISSUE TITLE
Codespace: try-space-sdk appears to be missing content

### ISSUE THREAD

**Issue by daweins** [microsoft/azure-orbital-space-sdk#27]
It has /var/spacedev, but no starter code nor documentation - is content missing (likely), or should we rename this something along the lines of blank-space-sdk and make this not the default

**Comment by daweins** [comment]
Move this to the bottom of the codespace list
Rename to base-host-platform

**Comment by alexlianides** [comment]
Fixed with https://github.com/microsoft/azure-orbital-space-sdk/pull/32
