### ISSUE TITLE
Codespace: python-starter-app fails to create

### ISSUE THREAD

**Issue by daweins** [microsoft/azure-orbital-space-sdk#30]
Create a new codespace w/ the python-starter-app config. It fails with "workspace failed to create"

Notice this error in the logs
"[ERROR]: app_name is a required parameter.  Please update your devcontainer.json and include '"app_name": "my-payload-app"'"

**Comment by daweins** [comment]
Hide this for now until we move over the whole solution

**Comment by alexlianides** [comment]
python starter has not been fully moved over. For now, reference the ship-detector-onxx smaple for a python payload-app sample
